### ISSUE TITLE
Syntax highlighting & Blockquotes

### ISSUE THREAD

**Issue by franile** [mientjan/react-native-markdown-renderer#11]
I hard coded the content of copyAll.js to my app but blockquotes did not render properly while the syntax highlighting did not show any text or format at all.
![22215355_1859944244016574_1464181057_n](https://user-images.githubusercontent.com/29992569/31126555-bb3da74a-a87e-11e7-8890-15fdfea4fc0f.jpg)
![22193194_1859943827349949_561277798_n](https://user-images.githubusercontent.com/29992569/31126563-bebe7a3e-a87e-11e7-8d79-124a8018598f.jpg)

**Comment by mientjan** [comment]
Hmmm let me take a look, ill come back to you in 3 hours

**Comment by uzeuze** [comment]
I'm having the same problem.

**Comment by mientjan** [comment]
Fixed issue in version 2.0.5

<img width="386" alt="screen shot 2017-10-13 at 19 57 21" src="https://user-images.githubusercontent.com/641320/31569378-eecee8b0-b050-11e7-9135-4a12d56861be.png">
<img width="383" alt="screen shot 2017-10-13 at 19 57 34" src="https://user-images.githubusercontent.com/641320/31569380-f2f655f4-b050-11e7-8f86-8e2a50472380.png">

**Comment by franile** [comment]
Thank you so much. I'll try this thanks again
