### ISSUE TITLE
Unable to use fontFamily on bold text

### ISSUE THREAD

**Issue by Amnesthesia** [mientjan/react-native-markdown-renderer#12]
Hi

It seems impossible to use custom fontFamily with bold text (I've tried adding it as style for emphasis, bold, strong, etc - nothing changes. Maybe this is because it's a nested text field and it insists on inheriting the same font family? It's really frustrating if you use a custom font, and therefore need another font for the "bold" version of the same font. :(

**Comment by mientjan** [comment]
I see the problem, So text is its own node when a fontFamily is defined for text this will then override the styling defined by strong. Im currently testing a fix to solve this.

**Comment by mientjan** [comment]
I have a fix for this in https://github.com/mientjan/react-native-markdown-renderer/tree/release/2.0.5 but i need to test it more to push for a 2.0.6 release.

**Comment by Amnesthesia** [comment]
Wow, that was quick! Thank you so much! <3

**Comment by Amnesthesia** [comment]
This problem is actually still present on Android, I think it's because the fontWeight property is set which makes custom fonts not work well on Android - I use a font that is already a bold font, but when fontWeight is set on Android, Android defaults to system font

**Comment by mientjan** [comment]
Awesome thx, will integrate your fix asap.

**Comment by mientjan** [comment]
So after a long while, i have a fix for this. its now in testing phase. release/3.0.0

**Comment by mientjan** [comment]
@Amnesthesia Do you have the markdown copy that triggers this problem. want to try and reproduce this on the new release/3.0.0 branch

**Comment by Amnesthesia** [comment]
sorry @mientjan, I just implemented the fix and shipped the app, no longer have the code that caused this but it was basically when loading markdown articles from Contentful, in which articles had **bold** text in the middle of sentences and especially if that bold text was inside other styled text, e.g ***bold and cursive***, or similarly

**Comment by mientjan** [comment]
Thx, i'm trying to reproduce this in the current version. But it is not occurring any more.
