### ISSUE TITLE
How to tell if someone clicked a specific link

### ISSUE THREAD

**Issue by isa3bel** [mientjan/react-native-markdown-renderer#130]
Hi,

I am interested in trying to determine when someone has clicked _a specific link_ within the markdown component. How would I be able to do this? It seems reasonable to create a callback for when someone has clicked the link but I need more guidance. Thanks for the help!

**Comment by iamacup** [comment]
Hi

using `react-native-markdown-display` [here](https://github.com/iamacup/react-native-markdown-display) - you can specify a callback as documented [here](https://github.com/iamacup/react-native-markdown-display#handling-links) that will handle your link or just do logging and handle it normally.

`react-native-markdown-display` is an exact copy of this library with all the relevant pull requests merged, the one you are talking about is #110
