### ISSUE TITLE
Views nested within a <Text> must have a width and height

### ISSUE THREAD

**Issue by dongodngtang** [mientjan/react-native-markdown-renderer#14]
Views nested within a <Text> must have a width and height

this write **![4444.jpg](http://deshpro.ufile.ucloud.com.cn/uploads/photo/2017/07/a95ec6b4218e6258e15ddc92916b0de8.jpg)** has error

**Comment by mientjan** [comment]
Yea, you cant have Views nested inside Text. can you give me the markdown copy so i can test this out and fix this bug.
