### ISSUE TITLE
Links don't render inline if paragraph is multiline

### ISSUE THREAD

**Issue by danilobuerger** [mientjan/react-native-markdown-renderer#19]
Version: 3.0.0

See Screenshot with default rules and styles.

<img width="451" alt="screen shot 2018-01-27 at 13 29 20" src="https://user-images.githubusercontent.com/996231/35471958-1d7af9ac-0366-11e8-9ff1-b942274c2a14.png">

**Comment by mientjan** [comment]
This fixes your issue, hope you enjoy the native markdown renderer.

**Comment by danilobuerger** [comment]
Works. Thanks for the quick fix!
