### ISSUE TITLE
How to ignore html comments?

### ISSUE THREAD

**Issue by jmatsushita** [mientjan/react-native-markdown-renderer#20]
When my markdown contains `<!-- comment -->` they get rendered as text.

How can I request to ignore them?

**Comment by mientjan** [comment]
There are 2 ways of doing it.

- Write a custom plugin with the PluginContainer.
- strip it away before it is send to markdown

```
<Markdown>{`
# Text
<!-- Comment -->

# Text
# Text
# Text
# Text
`.replace(/<!--[\s\S]*?(?:-->)/g, '')}
</Markdown>
```
