### ISSUE TITLE
The text in nested unordered lists is cut - iOS and Android

### ISSUE THREAD

**Issue by dbelchev** [mientjan/react-native-markdown-renderer#21]
Hey @mientjan, first of all thank you for the awesome library!!!

I saw that the text in nested unordered lists is cut both on iOS and Android.

<img width="313" alt="screen shot 2018-01-29 at 16 56 13" src="https://user-images.githubusercontent.com/9073252/35516803-61f01b2a-0515-11e8-8ceb-fd6e3f5ff411.png">

Thank you!

**Comment by mientjan** [comment]
Fixed, thx for spotting this.
