### ISSUE TITLE
Android - unordered list bullet is misaligned

### ISSUE THREAD

**Issue by dbelchev** [mientjan/react-native-markdown-renderer#22]
The bullet in the unordered lists on Android is misaligned.

<img width="242" alt="screen shot 2018-01-29 at 17 06 47" src="https://user-images.githubusercontent.com/9073252/35517450-2392a026-0517-11e8-9883-2ea7f6dab4c6.png">

**Comment by mientjan** [comment]
Fixed, thx for spotting this.

**Comment by dbelchev** [comment]
Awesome! Thank you!
