### ISSUE TITLE
Image resize

### ISSUE THREAD

**Issue by jmatsushita** [mientjan/react-native-markdown-renderer#23]
I'm using the approach below to load images, with a custom image rule but I can't find a way to get the image to not have empty margins at the top and bottom while displaying in full width.

Any advice?

Here's a link to the code below running in Snack: https://snack.expo.io/ByM5M1rIM

![image](https://user-images.githubusercontent.com/356097/35781589-0dd046ba-09ba-11e8-8df8-a21571cf2259.png)

```
import React, { Component } from 'react';
import {ScrollView, StyleSheet, Image } from 'react-native';
import { Constants } from 'expo';
import Markdown, { getUniqueID } from 'react-native-markdown-renderer'; // 3.0.2

const copy = `# h1 Heading 8-)

Before...

---

![](assets/1_introduction.png)

---

And after...

![](assets/expo.symbol.white.png)

`;

const images = {
  'assets/expo.symbol.white.png': require("./assets/expo.symbol.white.png"),
  'assets/1_introduction.png': require("./assets/1_introduction.png")
}

const rules = images => ({
  image: (node, children, parent, styles) => 
      <Image
        key={getUniqueID()}
        resizeMode="contain"
        style={StyleSheet.flatten([
          // {
          //   flex: 1
          // },
          styles.image
        ])}
        source={images[node.attributes.src]}
      />
});

import "@expo/vector-icons"; // 6.2.2

export default class App extends Component {
  render() {
    return (
      <ScrollView style={styles.container}>
        <Markdown rules={rules(images)}>{copy}</Markdown>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderColor: 'black',
    // alignItems: 'center',
    // justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  }
});
```

**Comment by mientjan** [comment]
Going to take a look

**Comment by mientjan** [comment]
Updated your stack, https://snack.expo.io/HkrED7vIM hope this works

**Comment by jmatsushita** [comment]
Thanks for the help! What I am trying to achieve is to have the margins smaller rather than the image being larger.

With your fix the image is cropped whereas I’m trying to displaying full width but with not too and bottom margins.

Is that possible?

**Comment by jmatsushita** [comment]
This is what I see with your update:

![image](https://user-images.githubusercontent.com/356097/35869096-4da5776a-0b2c-11e8-8db1-4876c9836075.png)

Note that it's possible to achieve the same effect simply by changing the `resize` props to 
```
resizeMode="cover"
```

What I would like to see is instead:
![image](https://user-images.githubusercontent.com/356097/35869375-e35bf0c2-0b2c-11e8-8da1-ee9b75deeceb.png)

**Comment by jmatsushita** [comment]
@mientjan If you have a bit of time to look again at my question, it would be much appreciated!

**Comment by jmatsushita** [comment]
@mientjan ?

**Comment by jmatsushita** [comment]
@mientjan please reopen. This is still not solved.
