### ISSUE TITLE
Add default support for Hardbreak

### ISSUE THREAD

**Issue by petrogad** [mientjan/react-native-markdown-renderer#29]
Currently it seems that hardbreak is not supported by default.  Right now, when I've seen this scenario creep up I've just added a custom rule to handle it, however it might be nice to just have at least a default for it to avoid others from having to do the same thing.

Thanks!

**Comment by mientjan** [comment]
What do you mean by hardbreak? How is that translated from markdown? So what is a hardbreak in markdown?

**Comment by petrogad** [comment]
It looks like an invisible character that can sometimes be copied into an editor.  I've added how I've been handling it right now as a custom rule (and how I believe a `<br>` would handle it in HTML).

**Comment by gambhiro** [comment]
Thanks for the great markdown library!

I ran into this issue as well.

Consider the following text, where the first two lines have two trailing spaces, which is translated as a forced newline (i.e hardbreak).

This kind of silent line break is not uncommon, is being used by some markdown flavours.

```
> barn's burnt down  
> without obstruction  
> now I see the moon
>
> *(Masahide)*
```

This will trigger the error:

```
Error: hardbreak renderRule not defined example: <Markdown rules={renderRules}>
```

It comes up in a situation when you are converting some other document to markdown, where the converter uses these silent line breaks, and so when it is inserted in the app, the lib will throw and error, (unless one expects this and strips it out during input validation).

**Comment by mientjan** [comment]
Thx @gambhiro for the great explanation. Going to take a look at this right away.
