### ISSUE TITLE
Autoconvert links with linkify

### ISSUE THREAD

**Issue by xanderberkein** [mientjan/react-native-markdown-renderer#31]
By default, non explicit links don't get autoconverted to links. The docs mention you can use linkify to autoconvert links:

> Autoconverted link https://github.com/nodeca/pica (enable linkify to see)

I had no luck trying to make linkify work with this library though. I tried implementing it like this:

```js
import linkify from 'linkify-it';
import Markdown, { PluginContainer } from 'react-native-markdown-renderer';

<Markdown style={styles} rules={rules} plugins={[new PluginContainer(linkify)]}>
  {text}
</Markdown>
```

but I got this error:
```
Error: (LinkifyIt) Invalid schema "inline": [object Object]
```

Can someone help me out here?

**Comment by mientjan** [comment]
Going to take a look at it

**Comment by xanderberkein** [comment]
Hi @mientjan, did you find the time already to take a look at this?

**Comment by mientjan** [comment]
yea, sorry for the super long wait, 

You can do this already

```
_markdownit = MarkdownIt({
      typographer: true,
**linkify: true,**
    }), 
renderer(){
  return <Markdown markdownit={this._markdownit}></Markdown> 
}
```

**Comment by xanderberkein** [comment]
That worked, thank you! Thanks for adding the docs too!
