### ISSUE TITLE
Support for local images referenced by path

### ISSUE THREAD

**Issue by hotdang-ca** [mientjan/react-native-markdown-renderer#32]
Would like to reference embedded images, not sure where the React Native packager puts the images, and therefore, not sure how to reference them in the path portion of an image.

Eg,

`![Image](./where/is/the/image.jpg)`

**Comment by mientjan** [comment]
Maybe you can make a pull?

In renderRules.js line 229 you see a rule
```
image: (node, children, parent, styles) => {
    return (
      <FitImage
        indicator={true}
        key={node.key}
        style={styles.image}
        source={{ uri: node.attributes.src }}
      />
    );
  }
```

by checking if the file is a external request or a local request you can make this also working locally.
**THIS IS PSEUDO CODE**
```js
image: (node, children, parent, styles) => {
    let url = null;
    if( isLocalURL(node.attributes.src)){
      url = require(node.attributes.src)
    } else {
      url = {uri: node.attributes.src}
    }
    return (
      <FitImage
        indicator={true}
        key={node.key}
        style={styles.image}
        source={url}
      />
    );
}
  }
```

**Comment by hotdang-ca** [comment]
Looks like a good approach. I'll have to research a few other things (specifically, assets handling, especially amongst different ReactNative Environments), but I'll contribute that PR in the coming weeks!

**Comment by nikugogoi** [comment]
@mientjan the solution you provide cant be implemented because of the way react native bundles.
It can be seen here https://facebook.github.io/react-native/docs/images#static-image-resources
We wont be able to use `require` with a variable.
Anyone found the solution?
