### ISSUE TITLE
Display image inside `link` custom rule

### ISSUE THREAD

**Issue by croogie** [mientjan/react-native-markdown-renderer#33]
Hi there,
I'm playing with library and I've encountered problem with displaying Image inside custom rule for image. It says that:

> Unexpected view type nested under text node...

Am I able to display anything which is not `Text` inside link. Is there any magic way to fix that? Any ideas?
Btw. What I want to achieve is to display youtube thumbnail when someone added link to youtube inside markdown.

**Comment by mientjan** [comment]
I'm currently working on that fix at the moment. I'm currently out of the
country so I will finish working on this fix in 4 days from now

**Comment by mientjan** [comment]
fixed issue in branch https://github.com/mientjan/react-native-markdown-renderer/tree/feature/issue-33 will merge soon. could you test it?

**Comment by mientjan** [comment]
tested it my self, released under v3.2.0. again thx for pointing this out
