### ISSUE TITLE
Expose "meta" and "markup" in nodes

### ISSUE THREAD

**Issue by olegbl** [mientjan/react-native-markdown-renderer#38]
tokensToAST loses some info when converting from markdownit tokens to react-native-markdown-renderer nodes.

The "meta" field would allow plugins to be able to pass down extra data to the token renderer. https://markdown-it.github.io/markdown-it/#Token.prototype.meta

The "markup" field would allow token renderers to distinguish between certain similar tokens (e.g. "strong" sources from `__strong__` vs. from `**strong**`) and render them appropriately. https://markdown-it.github.io/markdown-it/#Token.prototype.markup

Perhaps just exposing the source "token" on the "node" would solve this kind of issue going forward too.

**Comment by mientjan** [comment]
fixed, thx for pointing this out. added Info and Meta as sourceInfo and sourceMeta see version v3.2.0
