### ISSUE TITLE
[BUG] Links don't render correctly inline

### ISSUE THREAD

**Issue by bsnelder** [mientjan/react-native-markdown-renderer#4]
First of all thanks for the nice react-native markdown renderer. Looks promising!

**Description**
I'm using the following markdown:
```
This is a text. Click [here](https://google.com) to open a link. Let's add some more text to see how this behaves.
```
This renders like this:
<img width="375" alt="screen shot 2017-07-24 at 12 47 35" src="https://user-images.githubusercontent.com/25077318/28520094-77decb7a-706e-11e7-80e2-ea75b4f4db0c.png">

I expect the text to continue after the link here instead of rendering on a newline.

This is the web version of markdown-it, which does render as I want to on native as well:
<img width="581" alt="screen shot 2017-07-24 at 12 49 59" src="https://user-images.githubusercontent.com/25077318/28520144-a3523c4c-706e-11e7-80e1-939c35e773bc.png">

**Example / Solution**
I guess this is due the Text Elements rendering after each other instead of nested:
```
<Text>This is a text. Click</Text>
<Text onPress={() => console.log('clicked')}>here</Text>
<Text>to open a link. Let's add some more text to see how this behaves.</Text>
```
Versus:
```
<Text>This is a text. Click <Text onPress={() => console.log('clicked')}>here</Text> to open a link. Let's add some more text to see how this behaves.</Text>
```

Would it be easy to support this within the markdown renderer?

**Comment by mientjan** [comment]
Nice spot, really appreciate these reports. Did not encounter this before in the project i'm doing. Ill try to reproduce this issue and fix it but in the mean time you could try to add flexDirection: row to the paragraph ( p ), most text nodes have paragraph as there parent.

**Comment by mientjan** [comment]
Can reproduce it pretty easily 👍 , a quick fix would be to make the paragraph a Text element but this will break everything as soon as anything but a Text element is rendered inside the paragraph. The only solution is to group Text nodes that occur after each other.  Picking this up now.

**Comment by bsnelder** [comment]
Nice, sounds like that should work 👍. And for the paragraph already has flexDirection: 'row' as default styling and that's not working.

**Comment by mientjan** [comment]
Sorry for the delay, had a deadline. Fixed issue
