### ISSUE TITLE
Newline not actually on a new line

### ISSUE THREAD

**Issue by mcampsall** [mientjan/react-native-markdown-renderer#44]
Thanks so much for the library!

I do have an issue though, given the string: `"Word\nWord\nWord"` the output looks like:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/15930818/39783780-032d12b0-52cb-11e8-81c5-8f5eee2a5027.png">

This is only the case if the strings will all fit on one line. 

Given the string: `"This is a line. Is it long enough to stay?\nThis is a line. Is it long enough to stay?\nThis is a line. Is it long enough to stay?"` the output looks like:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/15930818/39783835-3670c1d0-52cb-11e8-8647-2dad127a0498.png">

Is there something I can do to get newlines to actually go on a new line?

**Comment by mientjan** [comment]
Maybe it's a bug, did a deploy of a new version today v3.2.0 so this could
be a bug I introduced today. I'll take a look at it tomorrow.

**Comment by mcampsall** [comment]
I think I am still on 3.1...
`"react-native-markdown-renderer": "^3.1.0",`

**Comment by mcampsall** [comment]
updated to 3.2 and the issue is still there

**Comment by mcampsall** [comment]
<img width="389" alt="screen shot 2018-05-15 at 1 19 13 pm" src="https://user-images.githubusercontent.com/15930818/40081361-997eb83c-5842-11e8-9a3e-df967314153d.png">
There is a strange space that gets added to the bottom of text as shown by the inspector in this pic. This only happens with a single `/n` and not `\n\n`

**Comment by mientjan** [comment]
deployed in v3.2.2, thx for pointing this out. Sorry it took to long.
