### ISSUE TITLE
Help on plugin implementation

### ISSUE THREAD

**Issue by diegolmello** [mientjan/react-native-markdown-renderer#49]
Hey, @mientjan.
This lib sounds **pretty awesome**.
I'm using another markdown lib at Rocket.Chat [here](https://github.com/RocketChat/Rocket.Chat.ReactNative), but I want to start using yours.

There is one thing I miss on it and seems to be already implemented, but I've been struggling for the past hours trying to make it work :P

**Plugins!**

Can you post a simple version of any plugin implemented?
Something like a hashtag recognition for example.
Markdown need to transform a hashtag on a `<Text>` with a `onPress` prop.

This:
`This is a #test`

Would turn onto this:
`This is a <Text onPress={() = alert('YEAH')}>#test</Text>`

I know there is some markdown-it plugins on npm, but I need to implement several of them from scratch.
Thanks for your help 👊

**Comment by mientjan** [comment]
ill add one tomorrow. to the wiki.

**Comment by mientjan** [comment]
@diegolmello Well what you want is actually already implemented see https://github.com/mientjan/react-native-markdown-renderer/wiki/Examples#enabling-linkify-feature
