### ISSUE TITLE
[BUG] Remove react / react-native dependencies

### ISSUE THREAD

**Issue by bsnelder** [mientjan/react-native-markdown-renderer#5]
**Description**
After installing react-native-markdown-renderer my tests (jest) fails with a lot of duplication errors like this one:

```
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: EventPluginRegistry
```

This is because react-native-markdown-renderer also installs react / react-native. I think the solution here would be to remove react / react-native from dependencies and move them to peerDependencies. If you want to you can add react / react-native to devDependencies as well to be able to install them when your working on the library itself.

I can make a PR if you agree:

```
"dependencies": {
    "markdown-it": "^8.3.1",
    "react-native-fit-image": "^1.4.9"
  },
  "peerDependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  },
  "devDependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  }
```

**Comment by mientjan** [comment]
Aaa thx, This has already been done will publish a new version. Someone else spotted this earlier.

**Comment by bsnelder** [comment]
Ah I see now! Would be nice if you can publish a new version to npm since this is blocking me from using the library right now. Thanks.

**Comment by bsnelder** [comment]
Any update on publishing the new package?

**Comment by mientjan** [comment]
New release has moved everything to a peer there corresponding peer dependency
