### ISSUE TITLE
Crash on hardbreak inside strong

### ISSUE THREAD

**Issue by olegbl** [mientjan/react-native-markdown-renderer#51]
Renderer crashes due to rendering `<View>` inside of `<Text>` when there's a linebreak inside of some inline styled text.

e.g.
```
**Foo  
Bar**
```
^ note the double space after "Foo"

**Comment by mientjan** [comment]
Hope I can take a look at it tomorrow. A bit swamped by work. Thx for
reporting this.

**Comment by mientjan** [comment]
I have a fix for this issue, as soon as i can get linked images to work again, then this will be deployed

**Comment by mientjan** [comment]
published https://www.npmjs.com/package/react-native-markdown-renderer/v/3.2.5 its in beta
