### ISSUE TITLE
Hard crash on Android

### ISSUE THREAD

**Issue by ckknight** [mientjan/react-native-markdown-renderer#56]
Unexpected view type nested under text node class abi28_0_0.com.facebook.react.uimanager.LayoutShadowNode

To reproduce:

```
<Markdown>{'a  \nb'}</Markdown>
```

The spaces followed by the newline seem to be the issue. `'a\nb'` is fine, so is `'a \nb'`

**Comment by mientjan** [comment]
Thx, will take a look at it

**Comment by mientjan** [comment]
Fixed issue in v3.2.8 was a issue with hardbreak being seen as a non block element.
