### ISSUE TITLE
Can i customize the markdown syntax instead of CommonMark syntax ?

### ISSUE THREAD

**Issue by tikkichan4** [mientjan/react-native-markdown-renderer#7]
Since i am developing an user-generated content project, i would like to display some content with markdown. But i dont want the user to use those markdown.

However, the user content may contains the syntax like **

I would like to customize the markdown syntax to avoid user using the markdown syntax, such as :
** to [bold][bold] 

Is it possible ? Thanks a lot.

**Comment by mientjan** [comment]
Sorry for the late reply, deadline. 

Well if i get this right, correct me if im wrong. But you want to customise the syntax used in markdown. Well i think this is possible but you need to start writing your own tokenize rules that replace the markdown rules.

This library uses markdown-it under the hood. And markdown-it has . a lot of features that i'm simply not using.

So in the Markdown component when the component is mounted a new created markdown-it parser is cerated.

You could override it by extending the Markdown component.

```js
import Markdown from 'react-native-markdown-renderer';
class AwesomeMarkdown extends Markdown {
  componentWillMount() {
    if (this.props.plugins && this.props.plugins.length > 0 && !this.md) {
      let md = MarkdownIt({
  html:         false,        // Enable HTML tags in source
  xhtmlOut:     false,        // Use '/' to close single tags (<br />).
                              // This is only for full CommonMark compatibility.
  breaks:       false,        // Convert '\n' in paragraphs into <br>
  langPrefix:   'language-',  // CSS language prefix for fenced blocks. Can be
                              // useful for external highlighters.
  linkify:      false,        // Autoconvert URL-like text to links

  // Enable some language-neutral replacement + quotes beautification
  typographer:  false,

  // Double + single quotes replacement pairs, when typographer enabled,
  // and smartquotes on. Could be either a String or an Array.
  //
  // For example, you can use '«»„“' for Russian, '„“‚‘' for German,
  // and ['«\xA0', '\xA0»', '‹\xA0', '\xA0›'] for French (including nbsp).
  quotes: '“”‘’',

  // Highlighter function. Should return escaped HTML,
  // or '' if the source string is not changed and should be escaped externaly.
  // If result starts with <pre... internal wrapper is skipped.
  highlight: function (/*str, lang*/) { return ''; }
});

      this.props.plugins.forEach(plugin => {
        md = md.use.apply(md, plugin.toArray());
      });

      this.md = md;
    }
  }
}
```
But this entire option list has not been tested yet. With the AstRenderer.

**Comment by mientjan** [comment]
v2.0 has the ability to add your custom markdownIt parser
