### ISSUE TITLE
New line pushes content out of parent view

### ISSUE THREAD

**Issue by bensinjin** [mientjan/react-native-markdown-renderer#81]
How do you accomplish something like this?

```
                <View style={{height: 20}}>
                    <Markdown>
                        {'# Line one \n # Line two'}
                    </Markdown>
                </View>
```

It seems the new line causes the markdown to flow out of the view with the constrained height.

**Comment by bensinjin** [comment]
So I've further confirmed this issue exists when there are newlines on the markdown.

**Comment by bensinjin** [comment]
The height of the parent container should be respected but it is not. The
content flows out of it but I need it not to as I’m creating a component
that is like a “show more” button that wraps the markdown component and
needs to be a fixed height when closed/collapsed.

**Comment by Norfeldt** [comment]
Could you provide some screenshots of it?

**Comment by bensinjin** [comment]
Code:
```
                <View style={{ height: 25 }}>
                    <Markdown>{'# This is line 1'}</Markdown>
                </View>
```
Output:
<img width="318" alt="screen shot 2018-10-01 at 10 51 11 am" src="https://user-images.githubusercontent.com/3228323/46306046-f951ef80-c567-11e8-85c9-a97187acbf4d.png">

This works as expected. The Text is cut off by the constrained height.

Code:
```
                <View style={{ height: 25 }}>
                    <Markdown>{'# This is a test \n # This is a test'}</Markdown>
                </View>
```
Output:
<img width="314" alt="screen shot 2018-10-01 at 10 54 10 am" src="https://user-images.githubusercontent.com/3228323/46306194-69f90c00-c568-11e8-84de-0c49d6d36194.png">

This does not work as expected. The Text flows out of the constrained height.

I've tried variations of styles on the `root` property (things like "overflow: 'none'") but that only sorta works and leads to other problems like the text not wrapping horizontally.

**Comment by Norfeldt** [comment]
I see what you mean. My guess would also be to try different `root` properties.

**Comment by bensinjin** [comment]
I think I’ve tried all to no avail :/

**Comment by bensinjin** [comment]
So I was able to get this to play nice with the following styles: 
```
        const style = {
            root: {
                // overflow: 'none' doesn't cuts of text horizontally .. scroll seems to work
                overflow: 'scroll' as 'scroll',
                height: 25,
            },
        };
```
Then:
```
                <View>
                    <Markdown style={style}>{'# This is a test \n # This is a test'}</Markdown>
                </View>
```
