### ISSUE TITLE
What's the typographer option?

### ISSUE THREAD

**Issue by jmatsushita** [mientjan/react-native-markdown-renderer#9]
mentioned in the docs, and how do I activate it?

Thanks!

Jun

**Comment by mientjan** [comment]
You cant i realized by your ticket that i did not enable this feature. Fill fix this as soon as possible.

**Comment by mientjan** [comment]
This is now enabled by default in version 2.0.
If you want to disable it do it like this.
```

<Markdown markdownit={MarkdownIt({
      typographer: false,
    })} >{markdownText}</Markdown>
```
